name: $(Date:yyyyMMdd)-$(Rev:rr)

parameters:
  - name: staticValidation
    displayName: Execute static validation
    type: boolean
    default: true
  - name: publishDesign
    displayName: Publish OpenAPI specification
    type: boolean
    default: true

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '/design/salesapi/*'
    exclude:
      - '/**/*.md'

variables:
  - template: '../../settings.yml'
  - name: openApiPath
    value: '$(azdoWorkDir)/design/salesapi/openapi_salesapi.json'
  - name: openApiUrl
    value: '$(ghRepo)/design/salesapi/openapi_salesapi.json'
  - name: currentApiVersion
    value: 'v2'
    

stages:
  - template: /.azuredevops/templates/stages.module.yml
    parameters:
      staticValidation: '${{ parameters.staticValidation }}'
      publishDesign: '${{ parameters.publishDesign }}'
      apiName: 'sales-api'
      apiTitle: 'Sales API'
      apiDescription: 'digitalize the sales'
      currentApiVersion: ${{variables.currentApiVersion}}


