openapi: 3.0.1
info:
  title: rocketapi
  version: '1.0'
paths:
  /rockets:
    get:
      tags:
        - rocketapi
      operationId: GetRocketNames
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RocketFile'
components:
  schemas:
    RocketFile:
      type: object
      properties:
        name:
          type: string
          nullable: true
        date:
          type: string
          format: date
        chanceOfFailure:
          type: integer
          format: int32
        keyCode:
          type: string
          nullable: true
          readOnly: true
      additionalProperties: false
