parameters:
  # Pipeline-related parameters
  poolName: '$(poolName)'
  vmImage: '$(vmImage)'
  defaultJobTimeoutInMinutes: 120
  serviceConnection: '$(serviceConnection)'
  # Logic-related parameters
  rg: 'rg-apicenter'
  apicName: 'myapicatalog'
  apiName: ''
  releaseDate: ''
  apiVersion: ''
  apicVersionName: ''
  environmentCode : ''
  environmentId: 'dev001xyz'
  lifecycleStage: 'development'
  azdoRunId: '$(azdoRunId)'

##---------------------------------------------##
## TEMPLATE LOGIC                              ##
##---------------------------------------------##
jobs:
  - deployment: ${{ parameters.environmentCode }}
    displayName: 'Deploy to ${{ parameters.environmentCode }} on ${{ parameters.environmentId }}'
    environment: ${{ parameters.environmentCode }}
    timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
    pool:
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
    strategy:
      runOnce:
        deploy:         
          steps:
            - checkout: self
            
            - task: AzureCLI@2  
              displayName: Debug
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  echo "... API version"
                  echo ${{ parameters.apiVersion }}

            - task: AzureCLI@2  
              displayName: APIC - Register deployment
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: 'bash'
                scriptLocation: inlineScript
                inlineScript: |
                  echo "------------DEPLOYMENT------------"
                  deploymentName="${{ parameters.environmentCode }}-${{ parameters.releaseDate }}-${{ parameters.apicVersionName }}"
                  deploymentId=$(echo "$deploymentName" | tr '.' '-')
                  deploymentId=$(echo "$deploymentId" | tr '_' '-')

                  environmentResource="/workspaces/default/environments/${{ parameters.environmentId }}"
                  definitionResource="/workspaces/default/apis/${{ parameters.apiName }}/versions/${{ parameters.apiVersion }}/definitions/xdef2024"
                  
                  echo "... deploymentName"
                  echo $deploymentName
                  echo "... environmentResource"
                  echo $environmentResource
                  echo "... definitionResource"
                  echo $definitionResource
                  echo "------------EXECUTE------------"
                  echo "... ****** az cli :: DEPLOYMENT CREATE command ******"
                  echo "az apic api deployment create -g ${{ parameters.rg }} -n ${{ parameters.apicName }} --deployment-id $deploymentId  --title $deploymentName --description $deploymentName --api-id '${{ parameters.apiName }}' --environment-id '$environmentResource' --definition-id '$definitionResource' --server runtime-uri[0]='${{ parameters.azdoRunId }}'"
                  echo "... Executing command"
                  az apic api deployment create -g ${{ parameters.rg }} -n ${{ parameters.apicName }} --deployment-id $deploymentId  --title $deploymentName --description $deploymentName --api-id "${{ parameters.apiName }}" --environment-id "$environmentResource" --definition-id "$definitionResource" --server runtime-uri[0]='${{ parameters.azdoRunId }}'

            - task: AzureCLI@2  
              displayName: APIC - Lifecycle
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: 'bash'
                scriptLocation: inlineScript
                inlineScript: |
                  echo "------------UPDATE-VERSION-LIFECYCLE------------"
                  echo "... ****** az cli :: VERSION UPDATE command ******"
                  echo "az apic api version update -g ${{ parameters.rg }} -n ${{ parameters.apicName }} --api-id ${{ parameters.apiName }} --version-id ${{ parameters.apiVersion }}  --lifecycle-stage ${{ parameters.lifecycleStage }}"
                  echo "... Executing command"
                  az apic api version update -g ${{ parameters.rg }} -n ${{ parameters.apicName }} --api-id ${{ parameters.apiName }} --version-id ${{ parameters.apiVersion }}  --lifecycle-stage ${{ parameters.lifecycleStage }}
