parameters:
  # Pipeline-related parameters
  poolName: '$(poolName)'
  vmImage: '$(vmImage)'
  defaultJobTimeoutInMinutes: 120
  serviceConnection: '$(serviceConnection)'
  # Logic-related parameters
  spectralRulesFullPath: '$(spectralRulesFullPath)'
  failSeverity: 'warn'
  openApiFilePath: '$(openApiFullPath)'
  # APIC parameters
  rg: 'rg-apicenter'
  apicName: 'myapicatalog'
  apiName: 'rocket-api'
  currentApiVersion: '$(currentApiVersion)'

##---------------------------------------------##
## TEMPLATE LOGIC                              ##
##---------------------------------------------##
jobs:
  - job:
    displayName: Publish API Design to API Center
    timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
    pool:
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
    steps:
      - checkout: self

      - script: cat ${{ parameters.openApiFilePath }}
        continueOnError: true
        displayName: 'Show OpenAPI spec'

      - task: AzureCLI@2
        displayName: 'JQ'
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: 'bash'
          scriptLocation: inlineScript
          inlineScript: |
            sudo apt --assume-yes install jq
            echo '##vso[task.setvariable variable=openApiContent]$( jq -c . ${{ parameters.openApiFilePath }} )'

      - bash: |
          echo "use macro syntax to read variables: $(openApiContent)"

      - task: AzureCLI@2  
        displayName: APIC - api list
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az apic api list -g ${{ parameters.rg }} -s ${{ parameters.apicName }}

      - task: AzureCLI@2  
        displayName: APIC - api create
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az apic api create -g ${{ parameters.rg }} -s ${{ parameters.apicName }} --name ${{ parameters.apiName }} --title "Rocket API" --kind rest --description "to the clouds and beyond" --summary "to the clouds and beyond"

      - task: AzureCLI@2  
        displayName: APIC - api version create
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az apic api version create -g ${{ parameters.rg }} -s ${{ parameters.apicName }} --api-name ${{ parameters.apiName }} --name 2024-01-01 --title "${{ parameters.currentApiVersion }}"

      - task: AzureCLI@2  
        displayName: APIC - api import specification
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            echo "... Creating definition "
            az apic api definition create -g ${{ parameters.rg }} -s ${{ parameters.apicName }} --api-name ${{ parameters.apiName }} --version 2024-01-01 --name "def001" --title "OpenAPI 3.0.1"
            echo ""
            echo "... Executing command :"
            echo "az apic api definition import-specification -g ${{ parameters.rg }} -s ${{ parameters.apicName }} --api-name ${{ parameters.apiName }} --version-name 2024-01-01 --definition-name "def001" --format "inline" --value '$(openApiContent)'"
            echo ""
            az apic api definition import-specification -g ${{ parameters.rg }} -s ${{ parameters.apicName }} --api-name ${{ parameters.apiName }} --version-name 2024-01-01 --definition-name "def001" --format "inline" --value '$(openApiContent)'

# az apic api definition import-specification -g api-center-test -s contosoeuap --api-name echo-api-2 --version-name 2023-08-01 --definition-name openapi3 --format "inline" --value '{"openapi":"3.0.1","info":{"title":"httpbin.org","description":"API Management facade for a very handy and free online HTTP tool.","version":"1.0"}}' --specification '{"name":"openapi","version":"3.0.0"}'
# az apic api register -g api-center-test -s contosoeuap --api-location "examples/cli-examples/spec-examples/openai.json" --environment-name public

