parameters:
  # Pipeline-related parameters
  poolName: '$(poolName)'
  vmImage: '$(vmImage)'
  defaultJobTimeoutInMinutes: 120
  # Logic-related parameters
  openApiFullPath: '$(openApiFullPath)'
  spectralRulesFullPath: '$(spectralRulesFullPath)'
  failSeverity: 'warn'

##---------------------------------------------##
## TEMPLATE LOGIC                              ##
##---------------------------------------------##
jobs:
  - job:
    displayName: Run Spectral validation
    timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
    pool:
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
    steps:
      - checkout: self

      - script: cat ${{ parameters.spectralRulesFullPath }}
        continueOnError: true
        displayName: 'Show OpenAPI rules'

      - script: cat ${{ parameters.openApiFullPath }}
        continueOnError: true
        displayName: 'Show OpenAPI spec'

      - script: sudo npm install -g @stoplight/spectral
        displayName: 'Install Linting Tool (stoplight/spectral)'

      - script: spectral lint ${{ parameters.openApiFullPath }} --ruleset ${{ parameters.spectralRulesFullPath }} --fail-severity "${{ parameters.failSeverity }}"
        displayName: 'Lint OpenAPI specs'