jobs:
  - job: Version
    displayName: Determine Version
    steps:
    - bash: |
        echo "##vso[build.updatebuildnumber]$(Pipeline.Version)"
        echo "Pipeline version is '$(Pipeline.Version)'"
      displayName: 'Change pipeline version $(Pipeline.Version)'