parameters:
  # Pipeline-related parameters
  poolName: '$(poolName)'
  vmImage: '$(vmImage)'
  defaultJobTimeoutInMinutes: 120
  serviceConnection: '$(serviceConnection)'
  # Logic-related parameters
  openApiFilePath: '$(openApiFilePath)'
  rulesetPath: '$(spectralRulesPath)'
  lintResult: '$(lintResult)'
  lintResultAzDO: '$(lintResultAzDO)'
  # warn, error
  failSeverity: 'error'
  # APIC parameters
  rg: 'rg-apicenter'
  apicName: 'myapicatalog'
  apiName: ''
  definitionId: 'xdef2024'
  azdoRunId: '$(azdoRunId)'

##---------------------------------------------##
## TEMPLATE LOGIC                              ##
##---------------------------------------------##
jobs:
  - job: Spectral
    displayName: Spectral
    timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
    pool:
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
    steps:
      - checkout: self

      - script: cat ${{ parameters.rulesetPath }}
        continueOnError: true
        displayName: 'Show OpenAPI rules'

      - script: cat ${{ parameters.openApiFilePath }}
        continueOnError: true
        displayName: 'Show OpenAPI spec'

      - script: sudo npm install -g @stoplight/spectral-cli --force
        displayName: 'Install Linting Tool (stoplight/spectral)'

      - bash: |
          spectral --version
          echo '... linting :: ${{ parameters.openApiFilePath }}'
          echo '... ruleset :: ${{ parameters.rulesetPath }}'
          echo '... failSeverity :: ${{ parameters.failSeverity }}'
        displayName: 'spectral parameters'

      - script: spectral lint "${{ parameters.openApiFilePath }}" --ruleset "${{ parameters.rulesetPath }}" --fail-severity "${{ parameters.failSeverity }}" --output "${{ parameters.lintResult }}" --format sarif --verbose
        continueOnError: true
        displayName: 'Lint OpenAPI file'

      - script: spectral lint "${{ parameters.openApiFilePath }}" --ruleset "${{ parameters.rulesetPath }}" --fail-severity "${{ parameters.failSeverity }}"
        continueOnError: true
        displayName: 'Lint OpenAPI pretty print'

      - script: cat ${{ parameters.lintResult }}
        continueOnError: true
        displayName: 'Show linting result (SARIF)'

      #Severity = "error" | "warning" | "information" | "hint";
      - bash: |
          fromSarifToApic=$(jq '{
              results: [.runs[0].results[] | {
              analyzer: "spectral",
              description: .message.text,
              analyzerRuleName: .ruleId,
              severity: (if .level == "warning" then "1" elif .level == "error" then "0" else "2" end),
              docUrl: .helpUri,
                  details: {
                      range: {
                          start: ((.locations[0].physicalLocation.region.startLine|tostring) + ":" + (.locations[0].physicalLocation.region.startColumn|tostring)),
                          end: ((.locations[0].physicalLocation.region.endLine|tostring) + ":" + (.locations[0].physicalLocation.region.endColumn|tostring))
                      }
                  }
              }]
          }' ${{ parameters.lintResult }})

          echo "... ***** APIC FORMATTED *****"
          echo $fromSarifToApic
         
          echo "... escaped json"
          escaped_json=$(echo "$fromSarifToApic" | tr -d '\n' | jq -c '.' | jq -Rs '.' | tr -d '\n')

          echo "... save to temp file"
          echo "$escaped_json" > "$(apiclintResultFilePathTemp)"
          
          fromApicToArm=$(jq -n --argfile value $(apiclintResultFilePathTemp) '{
            format: "inline",
            state: "completed",
            value: $value
          }')

          echo "... delete temp file"
          rm $(apiclintResultFilePathTemp)

          echo "... ***** ARM FORMATTED *****"
          echo $fromApicToArm

          echo "... save ARM format to $(apiclintResultFilePath)"
          echo "$fromApicToArm" > "$(apiclintResultFilePath)"
          # echo "... write azdo variable"
          # echo "##vso[task.setvariable variable=apicenterResultArmFormatted;]'$fromApicToArm'"
        displayName: 'Show formatted result (APIC and ARM)'

      - bash: |
          cat '$(apiclintResultFilePath)'
        displayName: 'Show apiclintResultFilePath content'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish artifact: linting result'
        inputs:
          targetPath: '$(apiclintResultFilePath)'
          artifact: 'linting'
          publishLocation: 'pipeline'
        condition: always()

      - script: spectral lint "${{ parameters.openApiFilePath }}" --ruleset "${{ parameters.rulesetPath }}" --fail-severity "${{ parameters.failSeverity }}" --output "${{ parameters.lintResultAzDO }}" --format junit
        continueOnError: true
        displayName: 'AzDO JUnit format'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '${{ parameters.lintResultAzDO }}'
          failTaskOnFailedTests: true
          testRunTitle: 'Spectral Linting Results'
        displayName: 'Publish Test Results'
  - job:
    displayName: BreakingChanges
    timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
    dependsOn:
      - spectral
    pool:
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
    steps:
      - checkout: self

      - script: sudo curl -fsSL https://raw.githubusercontent.com/tufin/oasdiff/main/install.sh | sh
        displayName: 'Install ChangeLog Tool'

      - task: AzureCLI@2
        displayName: 'concatenatedVersions'
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: 'bash'
          scriptLocation: inlineScript
          inlineScript: |
            jContent=$(jq -c . '${{ parameters.openApiFilePath }}')
            echo "##vso[task.setvariable variable=openApiContent;]$jContent"
            descriptionVersionOriginal=$(jq -r '.info.version' '${{ parameters.openApiFilePath }}')
            
            descriptionVersion=$(echo "$descriptionVersionOriginal" | tr '.' '-')
            apiVersion=$(echo ${{ parameters.currentApiVersion }} | tr '.' '-')
            
            concatenatedVersions=$(printf "%s---%s" "$apiVersion" "$descriptionVersion")
            echo $concatenatedVersions
            echo "##vso[task.setvariable variable=concatenatedVersions;]$concatenatedVersions"

            concatenatedVersionsName=$(printf "%s_%s" "$apiVersion" "$descriptionVersionOriginal")
            echo $concatenatedVersionsName
            echo "##vso[task.setvariable variable=concatenatedVersionsName;]$concatenatedVersionsName"

      - task: AzureCLI@2
        displayName: 'Get the N-1 version'
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "... Given the current version $(concatenatedVersions)"
            az apic api version list -g ${{ parameters.rg }} -n ${{ parameters.apicName }} --api-id ${{ parameters.apiName }} > input.json 

            previousVersionId=$(jq -r 'map(select(.name != "$(concatenatedVersions)")) | max_by(.name).name' input.json)
            echo "... The previous version id is $previousVersionId"
            echo "##vso[task.setvariable variable=previousVersionId;]$previousVersionId"

            echo "... Download the previous version"
            az apic api definition export-specification -g ${{ parameters.rg }} -n ${{ parameters.apicName }} --api-id ${{ parameters.apiName }} --version-id $previousVersionId --definition-id ${{ parameters.definitionId }} --file-name "$(azdoWorkDir)/previousversion.json"

      - bash: |
          oasdiff --version
          echo 'oasdiff changelog currentversion newversion'
          echo 'oasdiff changelog $(previousVersionId) $(concatenatedVersions)'
        displayName: 'ChangeLog Parameters'

      - script: oasdiff breaking --fail-on ERR "$(azdoWorkDir)/previousversion.json" "${{ parameters.openApiFilePath }}"
        continueOnError: false
        displayName: 'Breaking Changes check'


      - script: oasdiff changelog "$(azdoWorkDir)/previousversion.json" "${{ parameters.openApiFilePath }}" --color always
        continueOnError: true
        displayName: 'ChangeLog output'

