parameters:
  staticValidation: true
  publishDesign: true
  mocking: true
  defaultJobTimeoutInMinutes: 120
  apiName: ''

stages:
  - stage: validation
    displayName: Static validation
    condition: eq('${{ parameters.staticValidation }}', 'True')
    jobs:
      #- template: /.azuredevops/templates/jobs.pipelineVersion.yml
      - template: /.azuredevops/templates/jobs.validate_OpenApi.yml
        parameters:
          openApiFilePath: '$(openApiPath)'
          rulesetPath: '$(spectralRulesPath)'

  - stage: discovery
    displayName: Publish Open API design
    condition: and(eq('${{ parameters.publishDesign }}', 'True'), not(in(dependencies.validation.result, 'Failed', 'Canceled')))
    dependsOn:
      - validation
    jobs:
      - template: /.azuredevops/templates/jobs.publish_ApiDesign.yml
        parameters:
          openApiFilePath: '$(openApiPath)'
          currentApiVersion: $(Build.BuildNumber)
          apiName: '${{ parameters.apiName }}'

  - stage: mocking
    displayName: Publish to API Gateway
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('${{ parameters.mocking }}', 'True')))
    dependsOn:
      - validation
      - discovery
    jobs:
      - template: /.azuredevops/templates/jobs.enable_Mocking.yml
        parameters:
          openApiFilePath: '$(openApiPath)'
          currentApiVersion: $(Build.BuildNumber)
          apiName: '${{ parameters.apiName }}'

  - stage: dev
    displayName: Development
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
    dependsOn:
      - mocking
    jobs:
      - template: /.azuredevops/templates/jobs.deploy_Api.yml
        parameters:
          apiName: '${{ parameters.apiName }}'
          releaseDate: $(Build.BuildNumber)
          apiVersion: $(Build.BuildNumber)
          environmentCode : 'development'
          lifecycleStage: 'development'

  - stage: tst
    displayName: Testing
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
    dependsOn:
      - dev
    jobs:
      - template: /.azuredevops/templates/jobs.deploy_Api.yml
        parameters:
          apiName: '${{ parameters.apiName }}'
          releaseDate: $(Build.BuildNumber)
          apiVersion: $(Build.BuildNumber)
          environmentCode : 'testing'
          environmentId: 'tst001xyz'
          lifecycleStage: 'testing'

  - stage: stg
    displayName: Staging
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
    dependsOn:
      - tst
    jobs:
      - template: /.azuredevops/templates/jobs.deploy_Api.yml
        parameters:
          apiName: '${{ parameters.apiName }}'
          releaseDate: $(Build.BuildNumber)
          apiVersion: $(Build.BuildNumber)
          environmentCode : 'staging'
          environmentId: 'acc001xyz'
          lifecycleStage: 'preview'

  - stage: prd
    displayName: Production
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
    dependsOn:
      - stg
    jobs:
      - template: /.azuredevops/templates/jobs.deploy_Api.yml
        parameters:
          apiName: '${{ parameters.apiName }}'
          releaseDate: $(Build.BuildNumber)
          apiVersion: $(Build.BuildNumber)
          environmentCode : 'production'
          environmentId: 'prd001xyz'
          lifecycleStage: 'production'