variables:
  ###########################################################################################################################
  ################################################## Common Variables #######################################################
  ###########################################################################################################################


  azdoWorkDir: '$(System.DefaultWorkingDirectory)'
  azdoRunId: '$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)'
  ########################
  ##   Agent settings   ##
  ########################

  vmImage: 'ubuntu-latest' # Use this for Microsoft-hosted agents
  poolName: '' # Use this for self-hosted agents

  #############################
  ##   Validation settings   ##
  #############################

  # Static validation #
  # ----------------- #

  allowPreviewVersionsInAPITests: true # When enabled, preview versions do not fail the API version tests in the `module.tests.ps1` file

  # Deployment validation #
  # --------------------- #

  location: 'westeurope' # The default location to test deploy resources to
  spectralRulesPath: '$(azdoWorkDir)/rules/spectral-L1.oas.yaml'
  lintResult: '$(azdoWorkDir)/rules/lint-result.sarif'
  lintResultAzDO: '$(azdoWorkDir)/rules/lint-result.junit'
  apiclintResultFilePath: '$(azdoWorkDir)/rules/lint-result.json'
  apiclintResultFilePathTemp: '$(azdoWorkDir)/rules/temp.json'

  ###########################################################################################################################
  ################################################## Azure DevOps Only ######################################################
  ###########################################################################################################################

  #############################
  ##   Connection settings   ##
  #############################

  serviceConnection: 'codit-rnd-connection'
  subscriptionId: 'c1537527-c126-428d-8f72-1ac9f2c63c1f'

  ################
  ##   Source   ##
  ################

  vstsOrganizationURI: '$(System.CollectionUri)' # The URI of the TFS collection or Azure DevOps organization. For example: https://dev.azure.com/fabrikam/.
  vstsProject: '$(System.TeamProject)'
  pipelineFunctionsPath: 'utilities/pipelines'

  #################################
  #   Azure PowerShell Version   ##
  #################################

  # Should be set to 'latestVersion' unless there is an issue with the Az PowerShell modules.
  # If a specific version needs to be set azurePowerShellVersion should be changed to 'OtherVersion'.
  # NOTE: The strings are case sensitive and will not work unless properly entered.
  azurePowerShellVersion: 'latestVersion'
  # If using the latest version of the Az PowerShell modules, set `preferredAzurePowerShellVersion` to an empty string ''.
  # If overriding the Az PowerShell module version, set to the version. Example: '4.4.0'
  preferredAzurePowerShellVersion: ''
  
